services:
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: bev:dev
    container_name: bev_dev
    ports:
      - "8888:8888"            # Jupyter Lab
      - "6006:6006"            # TensorBoard
    volumes:
      # Monta la cartella principale del progetto live
      - ..:/workspace          
      
      # Mappatura dei dataset mantenendo lo stesso path dell'host per trasparenza con Hydra
      - /media/robesafe-sandra/Datos1/dataset:/media/robesafe-sandra/Datos1/dataset
      - /media/robesafe-sandra/Datos1/dataset_mini:/media/robesafe-sandra/Datos1/dataset_mini
      
      # Mantiene in cache i modelli scaricati
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - PYTHONPATH=/workspace/src
    ipc: host                  # Evita crash con PyTorch DataLoader
    shm_size: '8gb'            # Dimensione della memoria condivisa
    tty: true
    stdin_open: true
