defaults:
  - _self_
  - paths: veh.yaml

run_name: ${hydra:runtime.choices.paths}

hydra:
  run:
    dir: outputs/${run_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True

llm:
  name: Qwen/Qwen2.5-0.5B-Instruct

model:
  vision_hidden_size: 512
  vision_num_layers: 4
  vision_num_heads: 8
  num_queries: 100
  lora:
    r: 16
    alpha: 32
    dropout: 0.05

training:
  batch_size: 2 # batch size
  eval_batch_size: 8
  grad_accum: 8 # passaggi accumulati, batch size effettivo = batch_size X grad_accum
  lr: 2e-4
  num_epochs: 20
  num_workers: 6
  max_len: 200
  max_new_tokens: 20
  grad_clip: 1.0
  eval_max_batches: null
  early_stopping_patience: 5

data:
  train_fraction: 0.15
  val_fraction: 0.1